// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/bigquery/routines/v2/routines.proto

#include "google/cloud/bigquery/routines/v2/internal/routines_option_defaults.h"
#include "google/cloud/bigquery/routines/v2/routines_connection.h"
#include "google/cloud/bigquery/routines/v2/routines_options.h"
#include "google/cloud/internal/populate_common_options.h"
#include "google/cloud/internal/populate_grpc_options.h"
#include <memory>

namespace google {
namespace cloud {
namespace bigquery_routines_v2_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

namespace {
auto constexpr kBackoffScaling = 2.0;
}  // namespace

Options RoutinesDefaultOptions(Options options) {
  options = internal::PopulateCommonOptions(
      std::move(options), "GOOGLE_CLOUD_CPP_ROUTINES_ENDPOINT", "",
      "GOOGLE_CLOUD_CPP_ROUTINES_AUTHORITY", "bigquery.googleapis.com");
  options = internal::PopulateGrpcOptions(std::move(options));
  if (!options.has<bigquery_routines_v2::RoutinesRetryPolicyOption>()) {
    options.set<bigquery_routines_v2::RoutinesRetryPolicyOption>(
        bigquery_routines_v2::RoutinesLimitedTimeRetryPolicy(
            std::chrono::minutes(30))
            .clone());
  }
  if (!options.has<bigquery_routines_v2::RoutinesBackoffPolicyOption>()) {
    options.set<bigquery_routines_v2::RoutinesBackoffPolicyOption>(
        ExponentialBackoffPolicy(
            std::chrono::seconds(0), std::chrono::seconds(1),
            std::chrono::minutes(5), kBackoffScaling, kBackoffScaling)
            .clone());
  }
  if (!options.has<
          bigquery_routines_v2::RoutinesConnectionIdempotencyPolicyOption>()) {
    options.set<
        bigquery_routines_v2::RoutinesConnectionIdempotencyPolicyOption>(
        bigquery_routines_v2::MakeDefaultRoutinesConnectionIdempotencyPolicy());
  }

  return options;
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_routines_v2_internal
}  // namespace cloud
}  // namespace google
