// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source:
// google/cloud/bigquery/row_access_policies/v2/row_access_policies.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_ROW_ACCESS_POLICIES_V2_INTERNAL_ROW_ACCESS_POLICIES_REST_CONNECTION_IMPL_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_ROW_ACCESS_POLICIES_V2_INTERNAL_ROW_ACCESS_POLICIES_REST_CONNECTION_IMPL_H

#include "google/cloud/bigquery/row_access_policies/v2/internal/row_access_policies_rest_stub.h"
#include "google/cloud/bigquery/row_access_policies/v2/internal/row_access_policies_retry_traits.h"
#include "google/cloud/bigquery/row_access_policies/v2/row_access_policies_connection.h"
#include "google/cloud/bigquery/row_access_policies/v2/row_access_policies_connection_idempotency_policy.h"
#include "google/cloud/bigquery/row_access_policies/v2/row_access_policies_options.h"
#include "google/cloud/background_threads.h"
#include "google/cloud/backoff_policy.h"
#include "google/cloud/options.h"
#include "google/cloud/status_or.h"
#include "google/cloud/stream_range.h"
#include "google/cloud/version.h"
#include <memory>

namespace google {
namespace cloud {
namespace bigquery_row_access_policies_v2_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class RowAccessPoliciesRestConnectionImpl
    : public bigquery_row_access_policies_v2::RowAccessPoliciesConnection {
 public:
  ~RowAccessPoliciesRestConnectionImpl() override = default;

  RowAccessPoliciesRestConnectionImpl(
      std::unique_ptr<google::cloud::BackgroundThreads> background,
      std::shared_ptr<
          bigquery_row_access_policies_v2_internal::RowAccessPoliciesRestStub>
          stub,
      Options options);

  Options options() override { return options_; }

  StatusOr<google::cloud::cpp::bigquery::v2::Policy> GetIamPolicy(
      google::cloud::cpp::bigquery::row_access_policies::v2::
          GetIamPolicyRequest const& request) override;

  StreamRange<google::cloud::cpp::bigquery::v2::RowAccessPolicy>
  ListRowAccessPolicies(google::cloud::cpp::bigquery::row_access_policies::v2::
                            ListRowAccessPoliciesRequest request) override;

  StatusOr<google::cloud::cpp::bigquery::v2::TestIamPermissionsResponse>
  TestIamPermissions(google::cloud::cpp::bigquery::row_access_policies::v2::
                         TestIamPermissionsRequest const& request) override;

 private:
  static std::unique_ptr<
      bigquery_row_access_policies_v2::RowAccessPoliciesRetryPolicy>
  retry_policy(Options const& options) {
    return options
        .get<bigquery_row_access_policies_v2::
                 RowAccessPoliciesRetryPolicyOption>()
        ->clone();
  }

  static std::unique_ptr<BackoffPolicy> backoff_policy(Options const& options) {
    return options
        .get<bigquery_row_access_policies_v2::
                 RowAccessPoliciesBackoffPolicyOption>()
        ->clone();
  }

  static std::unique_ptr<bigquery_row_access_policies_v2::
                             RowAccessPoliciesConnectionIdempotencyPolicy>
  idempotency_policy(Options const& options) {
    return options
        .get<bigquery_row_access_policies_v2::
                 RowAccessPoliciesConnectionIdempotencyPolicyOption>()
        ->clone();
  }

  std::unique_ptr<google::cloud::BackgroundThreads> background_;
  std::shared_ptr<
      bigquery_row_access_policies_v2_internal::RowAccessPoliciesRestStub>
      stub_;
  Options options_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_row_access_policies_v2_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_ROW_ACCESS_POLICIES_V2_INTERNAL_ROW_ACCESS_POLICIES_REST_CONNECTION_IMPL_H
