// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source:
// google/cloud/bigquery/row_access_policies/v2/row_access_policies.proto

#include "google/cloud/bigquery/row_access_policies/v2/internal/row_access_policies_tracing_connection.h"
#include "google/cloud/internal/opentelemetry.h"
#include "google/cloud/internal/traced_stream_range.h"
#include <memory>
#include <utility>

namespace google {
namespace cloud {
namespace bigquery_row_access_policies_v2_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

#ifdef GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY

RowAccessPoliciesTracingConnection::RowAccessPoliciesTracingConnection(
    std::shared_ptr<
        bigquery_row_access_policies_v2::RowAccessPoliciesConnection>
        child)
    : child_(std::move(child)) {}

StatusOr<google::cloud::cpp::bigquery::v2::Policy>
RowAccessPoliciesTracingConnection::GetIamPolicy(
    google::cloud::cpp::bigquery::row_access_policies::v2::
        GetIamPolicyRequest const& request) {
  auto span = internal::MakeSpan(
      "bigquery_row_access_policies_v2::RowAccessPoliciesConnection::"
      "GetIamPolicy");
  auto scope = opentelemetry::trace::Scope(span);
  return internal::EndSpan(*span, child_->GetIamPolicy(request));
}

StreamRange<google::cloud::cpp::bigquery::v2::RowAccessPolicy>
RowAccessPoliciesTracingConnection::ListRowAccessPolicies(
    google::cloud::cpp::bigquery::row_access_policies::v2::
        ListRowAccessPoliciesRequest request) {
  auto span = internal::MakeSpan(
      "bigquery_row_access_policies_v2::RowAccessPoliciesConnection::"
      "ListRowAccessPolicies");
  internal::OTelScope scope(span);
  auto sr = child_->ListRowAccessPolicies(std::move(request));
  return internal::MakeTracedStreamRange<
      google::cloud::cpp::bigquery::v2::RowAccessPolicy>(std::move(span),
                                                         std::move(sr));
}

StatusOr<google::cloud::cpp::bigquery::v2::TestIamPermissionsResponse>
RowAccessPoliciesTracingConnection::TestIamPermissions(
    google::cloud::cpp::bigquery::row_access_policies::v2::
        TestIamPermissionsRequest const& request) {
  auto span = internal::MakeSpan(
      "bigquery_row_access_policies_v2::RowAccessPoliciesConnection::"
      "TestIamPermissions");
  auto scope = opentelemetry::trace::Scope(span);
  return internal::EndSpan(*span, child_->TestIamPermissions(request));
}

#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY

std::shared_ptr<bigquery_row_access_policies_v2::RowAccessPoliciesConnection>
MakeRowAccessPoliciesTracingConnection(
    std::shared_ptr<
        bigquery_row_access_policies_v2::RowAccessPoliciesConnection>
        conn) {
#ifdef GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY
  if (internal::TracingEnabled(conn->options())) {
    conn =
        std::make_shared<RowAccessPoliciesTracingConnection>(std::move(conn));
  }
#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY
  return conn;
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_row_access_policies_v2_internal
}  // namespace cloud
}  // namespace google
