// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/bigquery/tabledata/v2/tabledata.proto

#include "google/cloud/bigquery/tabledata/v2/tabledata_connection_idempotency_policy.h"
#include <memory>

namespace google {
namespace cloud {
namespace bigquery_tabledata_v2 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

using ::google::cloud::Idempotency;

TabledataConnectionIdempotencyPolicy::~TabledataConnectionIdempotencyPolicy() = default;

std::unique_ptr<TabledataConnectionIdempotencyPolicy>
TabledataConnectionIdempotencyPolicy::clone() const {
  return std::make_unique<TabledataConnectionIdempotencyPolicy>(*this);
}

Idempotency TabledataConnectionIdempotencyPolicy::InsertAll(google::cloud::cpp::bigquery::tabledata::v2::InsertAllRequest const&) {
  return Idempotency::kNonIdempotent;
}

Idempotency TabledataConnectionIdempotencyPolicy::ListTabledata(google::cloud::cpp::bigquery::tabledata::v2::ListTabledataRequest const&) {
  return Idempotency::kIdempotent;
}

std::unique_ptr<TabledataConnectionIdempotencyPolicy>
    MakeDefaultTabledataConnectionIdempotencyPolicy() {
  return std::make_unique<TabledataConnectionIdempotencyPolicy>();
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_tabledata_v2
}  // namespace cloud
}  // namespace google
