// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/bigquery/tabledata/v2/tabledata.proto

#include "google/cloud/bigquery/tabledata/v2/tabledata_client.h"
#include <memory>

namespace google {
namespace cloud {
namespace bigquery_tabledata_v2 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

TabledataClient::TabledataClient(
    std::shared_ptr<TabledataConnection> connection, Options opts)
    : connection_(std::move(connection)),
      options_(internal::MergeOptions(std::move(opts),
      connection_->options())) {}
TabledataClient::~TabledataClient() = default;

StatusOr<google::cloud::cpp::bigquery::v2::TableDataInsertAllResponse>
TabledataClient::InsertAll(std::string const& project_id, std::string const& dataset_id, std::string const& table_id, google::cloud::cpp::bigquery::v2::TableDataInsertAllRequest const& table_data_insert_all_request_resource, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  google::cloud::cpp::bigquery::tabledata::v2::InsertAllRequest request;
  request.set_project_id(project_id);
  request.set_dataset_id(dataset_id);
  request.set_table_id(table_id);
  *request.mutable_table_data_insert_all_request_resource() = table_data_insert_all_request_resource;
  return connection_->InsertAll(request);
}

StatusOr<google::cloud::cpp::bigquery::v2::TableDataInsertAllResponse>
TabledataClient::InsertAll(google::cloud::cpp::bigquery::tabledata::v2::InsertAllRequest const& request, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->InsertAll(request);
}

StatusOr<google::cloud::cpp::bigquery::v2::TableDataList>
TabledataClient::ListTabledata(std::string const& project_id, std::string const& dataset_id, std::string const& table_id, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  google::cloud::cpp::bigquery::tabledata::v2::ListTabledataRequest request;
  request.set_project_id(project_id);
  request.set_dataset_id(dataset_id);
  request.set_table_id(table_id);
  return connection_->ListTabledata(request);
}

StatusOr<google::cloud::cpp::bigquery::v2::TableDataList>
TabledataClient::ListTabledata(google::cloud::cpp::bigquery::tabledata::v2::ListTabledataRequest const& request, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->ListTabledata(request);
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_tabledata_v2
}  // namespace cloud
}  // namespace google
