// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "generator/internal/stub_cc_generator.h"
#include "generator/internal/codegen_utils.h"
#include "generator/internal/data_model.h"
#include "generator/internal/printer.h"
#include <google/protobuf/descriptor.h>

namespace pb = google::protobuf;

namespace google {
namespace codegen {
namespace internal {

std::vector<std::string> BuildClientStubCCIncludes(
    pb::ServiceDescriptor const* service) {
  return {
      LocalInclude(
          absl::StrCat(internal::ServiceNameToFilePath(service->full_name()),
                       "_stub" + GeneratedFileSuffix() + ".h")),
      LocalInclude("google/cloud/internal/compiler_info.h"),
      LocalInclude("google/cloud/internal/getenv.h"),
      LocalInclude("google/cloud/status_or.h"),
      LocalInclude("google/cloud/grpc_error_delegate.h"),
      LocalInclude("grpcpp/client_context.h"), LocalInclude("grpcpp/channel.h"),
      LocalInclude("grpcpp/create_channel.h"),
      // TODO(sdhart): change this to system once build issues are resolved
      LocalInclude(absl::StrCat(
          absl::StripSuffix(service->file()->name(), ".proto"), ".grpc.pb.h")),
      SystemInclude("google/longrunning/operations.grpc.pb.h")};
}

std::vector<std::string> BuildClientStubCCNamespaces(
    pb::ServiceDescriptor const* service) {
  std::vector<std::string> v = absl::StrSplit(service->file()->name(), '/');
  auto name = *--v.end();
  std::string inline_ns =
      absl::AsciiStrToUpper(absl::StripSuffix(name, ".proto")) + "_CLIENT_NS";
  return {"google", "cloud", std::string(absl::StripSuffix(name, ".proto")),
          inline_ns};
}

bool GenerateClientStubCC(pb::ServiceDescriptor const* service,
                          std::map<std::string, std::string> const& vars,
                          Printer& p, std::string* /* error */) {
  auto includes = BuildClientStubCCIncludes(service);
  auto namespaces = BuildClientStubCCNamespaces(service);

  p->Print(vars,
           "// Generated by the Codegen C++ plugin.\n"
           "// If you make any local changes, they will be lost.\n"
           "// source: $proto_file_name$\n"
           "\n");

  // includes
  for (auto const& include : includes) {
    p->Print("#include $include$\n", "include", include);
  }
  p->Print("\n");

  // namespace opener
  for (auto const& nspace : namespaces) {
    if (absl::EndsWith(nspace, "_CLIENT_NS")) {
      p->Print("inline namespace $namespace$ {\n", "namespace", nspace);
    } else {
      p->Print("namespace $namespace$ {\n", "namespace", nspace);
    }
  }
  p->Print("\n");

  // TODO(sdhart): get correct label for env var
  // ConnectionOptions implementation
  p->Print(vars,
           "std::string ConnectionOptionsTraits::default_endpoint() {\n"
           "  auto default_endpoint = google::cloud::internal::GetEnv(\n"
           "    \"GOOGLE_CLOUD_CPP_$class_name$_DEFAULT_ENDPOINT\");\n"
           "  return default_endpoint.has_value() ? *default_endpoint\n"
           "                           : \"$service_endpoint$\";\n"
           "}\n");
  p->Print(
      vars,
      "std::string ConnectionOptionsTraits::user_agent_prefix() {\n"
      "  return \"gcloud-cpp/\" + google::cloud::version_string() + \" (\" +\n"
      "    google::cloud::internal::CompilerId() + \"-\" + "
      "google::cloud::internal::CompilerVersion() + \"; \" +\n"
      "    google::cloud::internal::CompilerFeatures() + \")\";\n"
      "}\n");
  p->Print(
      vars,
      "int ConnectionOptionsTraits::default_num_channels() { return 4; }\n\n");

  // open internal namespace
  p->Print(vars, "namespace internal {\n");

  // default destructor for interface
  p->Print(vars, "$stub_class_name$::~$stub_class_name$() = default;\n\n");

  // define default stub class and constructor
  p->Print(vars,
           "class Default$stub_class_name$ : public $stub_class_name$ {\n"
           " public:\n"
           "  Default$stub_class_name$(\n"
           "      std::unique_ptr<$grpc_stub_fqn$::Stub> grpc_stub,\n"
           "      std::unique_ptr<google::longrunning::Operations::Stub> "
           "operations)\n"
           "      : grpc_stub_(std::move(grpc_stub)),\n"
           "        operations_(std::move(operations)) {}\n\n");

  // emit methods
  DataModel::PrintMethods(
      service, vars, p,
      "StatusOr<$response_object$>\n"
      "$method_name$(\n"
      "  grpc::ClientContext& client_context,\n"
      "  $request_object$ const& request) override {\n"
      "    $response_object$ response;\n"
      "    auto status =\n"
      "        grpc_stub_->$method_name$(&client_context, request, "
      "&response);\n"
      "    if (!status.ok()) {\n"
      "      return google::cloud::MakeStatusFromRpcError(status);\n"
      "    }\n"
      "    return response;"
      "}\n"
      "\n",
      NoStreamingPredicate);

  // private members and close class defintion
  p->Print(
      vars,
      " private:\n"
      "  std::unique_ptr<$grpc_stub_fqn$::Stub> grpc_stub_;\n"
      "  std::unique_ptr<google::longrunning::Operations::Stub> operations_;\n"
      "};\n\n");

  // implement factory function
  p->Print(
      vars,
      "std::shared_ptr<$stub_class_name$> CreateDefault$stub_class_name$(\n"
      "    ConnectionOptions options) {\n"
      "  auto channel =\n"
      "      grpc::CreateCustomChannel(options.endpoint(), "
      "options.credentials(),\n"
      "                                options.CreateChannelArguments());\n"
      "  auto service_grpc_stub = $grpc_stub_fqn$::NewStub(channel);\n"
      "  auto longrunning_grpc_stub =\n"
      "      google::longrunning::Operations::NewStub(channel);\n"
      "\n"
      "  std::shared_ptr<$stub_class_name$> stub =\n"
      "      std::make_shared<Default$stub_class_name$>(\n"
      "          std::move(service_grpc_stub), "
      "std::move(longrunning_grpc_stub));\n"
      "\n"
      "#if 0\n"
      "  // TODO(sdhart): add metadata support\n"
      "  stub = std::make_shared<DatabaseAdminMetadata>(std::move(stub));\n"
      "\n"
      "  // TODO(sdhart): add logging support\n"
      "  if (options.tracing_enabled(\"rpc\")) {\n"
      "    GCP_LOG(INFO) << \"Enabled logging for gRPC calls\";\n"
      "    stub = std::make_shared<DatabaseAdminLogging>(std::move(stub),\n"
      "                                                  "
      "options.tracing_options());\n"
      "  }\n"
      "#endif\n"
      "  return stub;\n"
      "}\n");

  p->Print(vars, "}  // namespace internal\n");
  std::reverse(namespaces.begin(), namespaces.end());
  for (auto const& nspace : namespaces) {
    p->Print("}  // namespace $namespace$\n", "namespace", nspace);
  }

  return true;

#if 0
  // Abstract stub method definitions
  DataModel::PrintMethods(
      service, vars, p,
      "StatusOr<$response_object$>\n"
      "$stub_class_name$::$method_name$(\n"
      "  grpc::ClientContext&,\n"
      "  $request_object$ const&) {\n"
      "  return Status(google::cloud::StatusCode::kUnimplemented,\n"
      "    \"$method_name$ not implemented\");\n"
      "}\n"
      "\n",
      NoStreamingPredicate);
#endif

#if 0
  // gRPC aware stub class declaration and method definition
  p->Print(vars,
           "namespace {\n"
           "class Default$stub_class_name$ : public $stub_class_name$ {\n"
           " public:\n"
           "  Default$stub_class_name$(std::unique_ptr<$grpc_stub_fqn$::"
           "StubInterface> grpc_stub)\n"
           "    : grpc_stub_(std::move(grpc_stub)) {}\n"
           "\n"
           "  Default$stub_class_name$(Default$stub_class_name$ const&) = "
           "delete;\n"
           "  Default$stub_class_name$& operator=(Default$stub_class_name$ "
           "const&) = delete;\n"
           "\n");
#endif

#if 0
  // todo(sdhart): handle return of respone type Empty correctly.
  DataModel::PrintMethods(
      service, vars, p,
      "  StatusOr<$response_object$>\n"
      "  $method_name$(grpc::ClientContext& context,\n"
      "    $request_object$ const& request) override {\n"
      "    $response_object$ response;\n"
      "    auto status = grpc_stub_->$method_name$(&context, request, "
      "&response);\n"
      "    if (!status.ok()) {\n"
      "      return google::cloud::MakeStatusFromRpcError(status);\n"
      "    }\n"
      "    return response;\n"
      "  }\n"
      "\n",
      NoStreamingPredicate);

  p->Print(vars,
           " private:\n"
           "  std::unique_ptr<$grpc_stub_fqn$::StubInterface> grpc_stub_;\n"
           "};  // Default$stub_class_name$\n"
           "\n");

  // TODO(sdhart): determine a mechanism to inject transient status codes during generation.
  p->Print(vars,
           "namespace internal {\n"
           "struct SafeGrpcRetry {\n"
           "  static inline bool IsOk(google::cloud::Status const& status) {\n"
           "    return status.ok();\n"
           "  }\n"
           "  static inline bool IsTransientFailure(google::cloud::Status const& status) {\n"
           "    return status.code() == StatusCode::kUnavailable ||\n"
           "      status.code() == StatusCode::kResourceExhausted;\n"
           "  }\n"
           "  static inline bool IsPermanentFailure(google::cloud::Status const& status) {\n"
           "    return !IsOk(status) && !IsTransientFailure(status);\n"
           "  }\n"
           "};\n"
           "}  // namespace internal\n"
           "\n");

  p->Print(vars,
           "/// The base class for retry policies.\n"
           "using RetryPolicy =\n"
           "  google::cloud::internal::RetryPolicy<google::cloud::Status,\n"
           "                                       internal::SafeGrpcRetry>;\n"
           "/// A retry policy that limits based on time.\n"
           "using LimitedTimeRetryPolicy =\n"
           "  google::cloud::internal::LimitedTimeRetryPolicy<google::cloud::Status,\n"
           "                                                  internal::SafeGrpcRetry>;\n"
           "/// A retry policy that limits the number of times a request can fail.\n"
           "using LimitedErrorCountRetryPolicy =\n"
           "  google::cloud::internal::LimitedErrorCountRetryPolicy<\n"
           "      google::cloud::Status, internal::SafeGrpcRetry>;\n"
           "\n");


  p->Print(vars,
      "class $stub_class_name$Impl : public $stub_class_name$ {\n"
      " public:\n"
      "  explicit $stub_class_name$Impl(\n"
      "      std::shared_ptr<internal::"

      )
#endif
#if 0
  // Retrying stub that decorates another stub
  p->Print(vars,
           "class Retry$stub_class_name$ : public $stub_class_name$ {\n"
           " public:\n"
           "  Retry$stub_class_name$(std::unique_ptr<$stub_class_name$> stub,\n"
           "                          RetryPolicy const& "
           "retry_policy,\n"
           "                          google::cloud::BackoffPolicy const& "
           "backoff_policy) :\n"
           "            next_stub_(std::move(stub)),\n"
           "            default_retry_policy_(retry_policy.clone()),\n"
           "            default_backoff_policy_(backoff_policy.clone()) {}\n"
           "\n");

  DataModel::PrintMethods(
      service, vars, p,
      "  google::cloud::Status\n"
      "  $method_name$(google::gax::CallContext& context,\n"
      "             $request_object$ const& request,\n"
      "             $response_object$* response) override {\n"
      "    auto invoke_stub = [this](google::gax::CallContext& c,\n"
      "                $request_object$ const& req,\n"
      "                $response_object$* resp) {\n"
      "              return this->next_stub_->$method_name$(c, req, resp);\n"
      "            };\n"
      "    return google::gax::MakeRetryCall<$request_object$,\n"
      "                                      $response_object$,\n"
      "                                      decltype(invoke_stub)>(\n"
      "        context, request, response, std::move(invoke_stub),\n"
      "        clone_retry(context), clone_backoff(context));\n"
      "  }\n"
      "\n",
      NoStreamingPredicate);

  p->Print(
      vars,
      " private:\n"
      "  std::unique_ptr<google::cloud::RetryPolicy>\n"
      "  clone_retry(google::gax::CallContext const &context) const {\n"
      "    auto context_retry = context.RetryPolicy();\n"
      "    return context_retry ? std::move(context_retry)\n"
      "                         : std::move(default_retry_policy_->clone());\n"
      "  }\n"
      "\n"
      "  std::unique_ptr<google::cloud::BackoffPolicy>\n"
      "  clone_backoff(google::gax::CallContext const &context) const {\n"
      "    auto context_backoff = context.BackoffPolicy();\n"
      "    return context_backoff ? std::move(context_backoff)\n"
      "                           : "
      "std::move(default_backoff_policy_->clone());\n"
      "  }\n"
      "\n"
      "  std::unique_ptr<$stub_class_name$> next_stub_;\n"
      "  const std::unique_ptr<RetryPolicy const> "
      "default_retry_policy_;\n"
      "  const std::unique_ptr<google::cloud::BackoffPolicy const>  "
      "default_backoff_policy_;\n"
      "};  // Retry$stub_class_name$\n");
#endif
#if 0
  // todo(sdhart): fix this
  p->Print(vars,
           "}  // namespace\n"
           "\n"
           "std::unique_ptr<$stub_class_name$> Create$stub_class_name$() {\n"
           "  auto credentials = grpc::GoogleDefaultCredentials();\n"
           "  return Create$stub_class_name$(std::move(credentials));\n"
           "}\n");

  p->Print(vars,
           "\n"
           "std::unique_ptr<$stub_class_name$>\n"
           "Create$stub_class_name$(std::shared_ptr<grpc::ChannelCredentials> "
           "creds) {\n"
           "  auto channel = grpc::CreateChannel(\"$service_endpoint$\",\n"
           "    std::move(creds));\n"
           "  auto grpc_stub = $grpc_stub_fqn$::NewStub(std::move(channel));\n"
           "  auto default_stub = std::unique_ptr<$stub_class_name$>(new\n"
           "    Default$stub_class_name$(std::move(grpc_stub)));\n"
           "  using ms = std::chrono::milliseconds;\n"
           "  // Note: these retry and backoff times are dummy stand ins.\n"
           "  // More appopriate default values will be chosen later.\n"
           "  LimitedDurationRetryPolicy<> retry_policy(ms(500), "
           "ms(500));\n"
           "  google::cloud::ExponentialBackoffPolicy backoff_policy(ms(20), "
           "ms(100));\n"
           "  return std::unique_ptr<$stub_class_name$>(new "
           "Retry$stub_class_name$(\n"
           "                       std::move(default_stub),\n"
           "                       retry_policy,\n"
           "                       backoff_policy));\n"
           "}\n"
           "\n");
#endif
}

}  // namespace internal
}  // namespace codegen
}  // namespace google
