// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "generator/internal/stub_factory_generator.h"
#include "absl/memory/memory.h"
#include "absl/strings/str_cat.h"
#include "absl/strings/str_replace.h"
#include "absl/strings/str_split.h"
#include "absl/strings/strip.h"
#include "generator/internal/codegen_utils.h"
#include "generator/internal/predicate_utils.h"
#include "generator/internal/printer.h"
#include <google/api/client.pb.h>
#include <google/protobuf/descriptor.h>

namespace google {
namespace cloud {
namespace generator_internal {

Status StubFactoryGenerator::PrintMethod(
    google::protobuf::MethodDescriptor const& method,
    std::map<std::string, std::string> vars, std::vector<Pattern> patterns) {
  std::vector<Pattern> matching_patterns;
  for (auto const& p : patterns) {
    if (p.predicate(method)) {
      matching_patterns.push_back(p);
    }
  }

  if (matching_patterns.empty())
    return Status(StatusCode::kNotFound,
                  "No matching patterns for: " + method.full_name());
  if (matching_patterns.size() > 1)
    return Status(StatusCode::kInternal,
                  "More than one pattern found for: " + method.full_name());
  for (auto const& f : matching_patterns[0].fragments) {
    header_.Print(__LINE__, __FILE__, vars, f(method));
  }
  return {};
}

StubFactoryGenerator::StubFactoryGenerator(
    google::protobuf::ServiceDescriptor const* service_descriptor,
    std::map<std::string, std::string> service_vars,
    std::map<std::string, std::map<std::string, std::string>>
        service_method_vars,
    google::protobuf::compiler::GeneratorContext* context)
    : service_descriptor_(service_descriptor),
      service_vars_(std::move(service_vars)),
      service_method_vars_(std::move(service_method_vars)),
      header_(context, service_vars_["stub_factory_header_path"]),
      cc_(context, service_vars_["stub_factory_cc_path"]) {
  SetVars();
}

Status StubFactoryGenerator::GenerateHeader() {
  // Temporary conditional for unit testing purposes.
  if (service_descriptor_->name() == "FailureService") {
    return Status(StatusCode::kInternal, "Failed for testing.");
  }

  header_.Print(CopyrightLicenseFileHeader());
  header_.Print(service_vars_,  // clang-format off
    "// Generated by the Codegen C++ plugin.\n"
    "// If you make any local changes, they will be lost.\n"
    "// source: $proto_file_name$\n"
    "#ifndef $stub_factory_header_include_guard$\n"
    "#define $stub_factory_header_include_guard$\n"
    "\n");
  // clang-format on

  // includes
  header_.Print(LocalInclude("google/cloud/backoff_policy.h"));
  header_.Print(LocalInclude("google/cloud/connection_options.h"));
  header_.Print(LocalInclude("google/cloud/internal/retry_policy.h"));
  header_.Print(LocalInclude("google/cloud/polling_policy.h"));
  header_.Print(LocalInclude("google/cloud/status_or.h"));
  header_.Print(LocalInclude("grpcpp/security/credentials.h"));
  header_.Print(SystemInclude(absl::StrCat(
      absl::StripSuffix(service_descriptor_->file()->name(), ".proto"),
      ".grpc.pb.h")));
  header_.Print(SystemInclude("memory"));
  header_.Print(SystemInclude("string"));
  header_.Print("\n");

  // namespace openers
  auto namespaces =
      BuildNamespaces(service_vars_, NamespaceType::kInternal).value();
  for (auto const& nspace : namespaces) {
    if (absl::EndsWith(nspace, "_CLIENT_NS")) {
      header_.Print("inline namespace $namespace$ {\n", "namespace", nspace);
    } else {
      header_.Print("namespace $namespace$ {\n", "namespace", nspace);
    }
  }
  header_.Print("\n");

  // connection options
  header_.Print(  // clang-format off
    "struct ConnectionOptionsTraits {\n"
    "  static std::string default_endpoint();\n"
    "  static std::string user_agent_prefix();\n"
    "  static int default_num_channels();\n"
    "};\n\n");
  // clang-format on
  header_.Print(  // clang-format off
    "using ConnectionOptions =\n"
    "  google::cloud::ConnectionOptions<ConnectionOptionsTraits>;\n\n");
  // clang-format on

  header_.Print(
      service_vars_,  // clang-format off
    "std::shared_ptr<$stub_class_name$>\n"
    "CreateDefault$stub_class_name$(ConnectionOptions options);\n\n");
  // clang-format on

  // namespace closers
  std::reverse(namespaces.begin(), namespaces.end());
  for (auto const& nspace : namespaces) {
    header_.Print("}  // namespace $namespace$\n", "namespace", nspace);
  }
  header_.Print("\n");

  // close header guard
  header_.Print(service_vars_,  // clang-format off
      "#endif  // $stub_factory_header_include_guard$\n");
  // clang-format on
  return {};
}

Status StubFactoryGenerator::Generate() { return GenerateHeader(); }

void StubFactoryGenerator::SetVars() {
  service_vars_["stub_factory_header_include_guard"] = absl::StrCat(
      "GOOGLE_CLOUD_CPP_", absl::AsciiStrToUpper(absl::StrReplaceAll(
                               service_vars_["stub_factory_header_path"],
                               {{"/", "_"}, {".", "_"}})));
}

}  // namespace generator_internal
}  // namespace cloud
}  // namespace google
