// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/bigquery/row_access_policies/v2/row_access_policies.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_ROW_ACCESS_POLICIES_V2_ROW_ACCESS_POLICIES_CONNECTION_IDEMPOTENCY_POLICY_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_ROW_ACCESS_POLICIES_V2_ROW_ACCESS_POLICIES_CONNECTION_IDEMPOTENCY_POLICY_H

#include "google/cloud/idempotency.h"
#include "google/cloud/version.h"
#include <google/cloud/bigquery/row_access_policies/v2/row_access_policies.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace bigquery_row_access_policies_v2 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class RowAccessPoliciesConnectionIdempotencyPolicy {
 public:
  virtual ~RowAccessPoliciesConnectionIdempotencyPolicy();

  /// Create a new copy of this object.
  virtual std::unique_ptr<RowAccessPoliciesConnectionIdempotencyPolicy> clone() const;

  virtual google::cloud::Idempotency
  GetIamPolicy(google::cloud::cpp::bigquery::row_access_policies::v2::GetIamPolicyRequest const& request);

  virtual google::cloud::Idempotency
  ListRowAccessPolicies(google::cloud::cpp::bigquery::row_access_policies::v2::ListRowAccessPoliciesRequest request);

  virtual google::cloud::Idempotency
  TestIamPermissions(google::cloud::cpp::bigquery::row_access_policies::v2::TestIamPermissionsRequest const& request);
};

std::unique_ptr<RowAccessPoliciesConnectionIdempotencyPolicy>
    MakeDefaultRowAccessPoliciesConnectionIdempotencyPolicy();

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_row_access_policies_v2
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_ROW_ACCESS_POLICIES_V2_ROW_ACCESS_POLICIES_CONNECTION_IDEMPOTENCY_POLICY_H
