// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source:
// google/cloud/bigquery/row_access_policies/v2/row_access_policies.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_ROW_ACCESS_POLICIES_V2_ROW_ACCESS_POLICIES_CLIENT_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_ROW_ACCESS_POLICIES_V2_ROW_ACCESS_POLICIES_CLIENT_H

#include "google/cloud/bigquery/row_access_policies/v2/row_access_policies_rest_connection.h"
#include "google/cloud/future.h"
#include "google/cloud/options.h"
#include "google/cloud/polling_policy.h"
#include "google/cloud/status_or.h"
#include "google/cloud/version.h"
#include <memory>
#include <string>

namespace google {
namespace cloud {
namespace bigquery_row_access_policies_v2 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

///
/// Service for the rowAccessPolicies resource.
/// https://cloud.google.com/bigquery/docs/reference/rest/v2/rowAccessPolicies
///
/// @par Equality
///
/// Instances of this class created via copy-construction or copy-assignment
/// always compare equal. Instances created with equal
/// `std::shared_ptr<*Connection>` objects compare equal. Objects that compare
/// equal share the same underlying resources.
///
/// @par Performance
///
/// Creating a new instance of this class is a relatively expensive operation,
/// new objects establish new connections to the service. In contrast,
/// copy-construction, move-construction, and the corresponding assignment
/// operations are relatively efficient as the copies share all underlying
/// resources.
///
/// @par Thread Safety
///
/// Concurrent access to different instances of this class, even if they compare
/// equal, is guaranteed to work. Two or more threads operating on the same
/// instance of this class is not guaranteed to work. Since copy-construction
/// and move-construction is a relatively efficient operation, consider using
/// such a copy when using this class from multiple threads.
///
class RowAccessPoliciesClient {
 public:
  explicit RowAccessPoliciesClient(
      std::shared_ptr<RowAccessPoliciesConnection> connection,
      Options opts = {});
  ~RowAccessPoliciesClient();

  ///@{
  /// @name Copy and move support
  RowAccessPoliciesClient(RowAccessPoliciesClient const&) = default;
  RowAccessPoliciesClient& operator=(RowAccessPoliciesClient const&) = default;
  RowAccessPoliciesClient(RowAccessPoliciesClient&&) = default;
  RowAccessPoliciesClient& operator=(RowAccessPoliciesClient&&) = default;
  ///@}

  ///@{
  /// @name Equality
  friend bool operator==(RowAccessPoliciesClient const& a,
                         RowAccessPoliciesClient const& b) {
    return a.connection_ == b.connection_;
  }
  friend bool operator!=(RowAccessPoliciesClient const& a,
                         RowAccessPoliciesClient const& b) {
    return !(a == b);
  }
  ///@}

  // clang-format off
  ///
  /// Gets the access control policy for a resource. Returns an empty policy if
  /// the resource exists and does not have a policy set.
  /// https://cloud.google.com/bigquery/docs/reference/rest/v2/rowAccessPolicies/getIamPolicy
  ///
  /// @param resource  REQUIRED: The resource for which the policy is being requested. See
  ///  [Resource names](https://cloud.google.com/apis/design/resource_names) for
  ///  the appropriate value for this field.
  /// @param get_iam_policy_request_resource  The GetIamPolicyRequest for this request.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return the result of the RPC. The response message type
  ///     ([google.cloud.cpp.bigquery.v2.Policy])
  ///     is mapped to a C++ class using the [Protobuf mapping rules].
  ///     If the request fails, the [`StatusOr`] contains the error details.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.cpp.bigquery.row_access_policies.v2.GetIamPolicyRequest]: @cloud_cpp_reference_link{google/cloud/bigquery/row_access_policies/v2/row_access_policies.proto#L80}
  /// [google.cloud.cpp.bigquery.v2.Policy]: @cloud_cpp_reference_link{google/cloud/bigquery/v2/internal/common_003.proto#L230}
  ///
  // clang-format on
  StatusOr<google::cloud::cpp::bigquery::v2::Policy> GetIamPolicy(
      std::string const& resource,
      google::cloud::cpp::bigquery::v2::GetIamPolicyRequest const&
          get_iam_policy_request_resource,
      Options opts = {});

  // clang-format off
  ///
  /// Gets the access control policy for a resource. Returns an empty policy if
  /// the resource exists and does not have a policy set.
  /// https://cloud.google.com/bigquery/docs/reference/rest/v2/rowAccessPolicies/getIamPolicy
  ///
  /// @param request Unary RPCs, such as the one wrapped by this
  ///     function, receive a single `request` proto message which includes all
  ///     the inputs for the RPC. In this case, the proto message is a
  ///     [google.cloud.cpp.bigquery.row_access_policies.v2.GetIamPolicyRequest].
  ///     Proto messages are converted to C++ classes by Protobuf, using the
  ///     [Protobuf mapping rules].
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return the result of the RPC. The response message type
  ///     ([google.cloud.cpp.bigquery.v2.Policy])
  ///     is mapped to a C++ class using the [Protobuf mapping rules].
  ///     If the request fails, the [`StatusOr`] contains the error details.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.cpp.bigquery.row_access_policies.v2.GetIamPolicyRequest]: @cloud_cpp_reference_link{google/cloud/bigquery/row_access_policies/v2/row_access_policies.proto#L80}
  /// [google.cloud.cpp.bigquery.v2.Policy]: @cloud_cpp_reference_link{google/cloud/bigquery/v2/internal/common_003.proto#L230}
  ///
  // clang-format on
  StatusOr<google::cloud::cpp::bigquery::v2::Policy> GetIamPolicy(
      google::cloud::cpp::bigquery::row_access_policies::v2::
          GetIamPolicyRequest const& request,
      Options opts = {});

  // clang-format off
  ///
  /// Lists all row access policies on the specified table.
  /// https://cloud.google.com/bigquery/docs/reference/rest/v2/rowAccessPolicies/list
  ///
  /// @param project_id  Required. Project ID of the row access policies to list.
  /// @param dataset_id  Required. Dataset ID of row access policies to list.
  /// @param table_id  Required. Table ID of the table to list row access policies.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return a [StreamRange](@ref google::cloud::StreamRange)
  ///     to iterate of the results. See the documentation of this type for
  ///     details. In brief, this class has `begin()` and `end()` member
  ///     functions returning a iterator class meeting the
  ///     [input iterator requirements]. The value type for this iterator is a
  ///     [`StatusOr`] as the iteration may fail even after some values are
  ///     retrieved successfully, for example, if there is a network disconnect.
  ///     An empty set of results does not indicate an error, it indicates
  ///     that there are no resources meeting the request criteria.
  ///     On a successful iteration the `StatusOr<T>` contains elements of type
  ///     [google.cloud.cpp.bigquery.v2.RowAccessPolicy], or rather,
  ///     the C++ class generated by Protobuf from that type. Please consult the
  ///     Protobuf documentation for details on the [Protobuf mapping rules].
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.cpp.bigquery.row_access_policies.v2.ListRowAccessPoliciesRequest]: @cloud_cpp_reference_link{google/cloud/bigquery/row_access_policies/v2/row_access_policies.proto#L93}
  /// [google.cloud.cpp.bigquery.v2.RowAccessPolicy]: @cloud_cpp_reference_link{google/cloud/bigquery/v2/internal/common_013.proto#L39}
  ///
  // clang-format on
  StreamRange<google::cloud::cpp::bigquery::v2::RowAccessPolicy>
  ListRowAccessPolicies(std::string const& project_id,
                        std::string const& dataset_id,
                        std::string const& table_id, Options opts = {});

  // clang-format off
  ///
  /// Lists all row access policies on the specified table.
  /// https://cloud.google.com/bigquery/docs/reference/rest/v2/rowAccessPolicies/list
  ///
  /// @param request Unary RPCs, such as the one wrapped by this
  ///     function, receive a single `request` proto message which includes all
  ///     the inputs for the RPC. In this case, the proto message is a
  ///     [google.cloud.cpp.bigquery.row_access_policies.v2.ListRowAccessPoliciesRequest].
  ///     Proto messages are converted to C++ classes by Protobuf, using the
  ///     [Protobuf mapping rules].
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return a [StreamRange](@ref google::cloud::StreamRange)
  ///     to iterate of the results. See the documentation of this type for
  ///     details. In brief, this class has `begin()` and `end()` member
  ///     functions returning a iterator class meeting the
  ///     [input iterator requirements]. The value type for this iterator is a
  ///     [`StatusOr`] as the iteration may fail even after some values are
  ///     retrieved successfully, for example, if there is a network disconnect.
  ///     An empty set of results does not indicate an error, it indicates
  ///     that there are no resources meeting the request criteria.
  ///     On a successful iteration the `StatusOr<T>` contains elements of type
  ///     [google.cloud.cpp.bigquery.v2.RowAccessPolicy], or rather,
  ///     the C++ class generated by Protobuf from that type. Please consult the
  ///     Protobuf documentation for details on the [Protobuf mapping rules].
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.cpp.bigquery.row_access_policies.v2.ListRowAccessPoliciesRequest]: @cloud_cpp_reference_link{google/cloud/bigquery/row_access_policies/v2/row_access_policies.proto#L93}
  /// [google.cloud.cpp.bigquery.v2.RowAccessPolicy]: @cloud_cpp_reference_link{google/cloud/bigquery/v2/internal/common_013.proto#L39}
  ///
  // clang-format on
  StreamRange<google::cloud::cpp::bigquery::v2::RowAccessPolicy>
  ListRowAccessPolicies(google::cloud::cpp::bigquery::row_access_policies::v2::
                            ListRowAccessPoliciesRequest request,
                        Options opts = {});

  // clang-format off
  ///
  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of permissions, not
  /// a `NOT_FOUND` error. Note: This operation is designed to be used for
  /// building permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  /// https://cloud.google.com/bigquery/docs/reference/rest/v2/rowAccessPolicies/testIamPermissions
  ///
  /// @param resource  REQUIRED: The resource for which the policy detail is being requested. See
  ///  [Resource names](https://cloud.google.com/apis/design/resource_names) for
  ///  the appropriate value for this field.
  /// @param test_iam_permissions_request_resource  The TestIamPermissionsRequest for this request.
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return the result of the RPC. The response message type
  ///     ([google.cloud.cpp.bigquery.v2.TestIamPermissionsResponse])
  ///     is mapped to a C++ class using the [Protobuf mapping rules].
  ///     If the request fails, the [`StatusOr`] contains the error details.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.cpp.bigquery.row_access_policies.v2.TestIamPermissionsRequest]: @cloud_cpp_reference_link{google/cloud/bigquery/row_access_policies/v2/row_access_policies.proto#L116}
  /// [google.cloud.cpp.bigquery.v2.TestIamPermissionsResponse]: @cloud_cpp_reference_link{google/cloud/bigquery/v2/internal/common_003.proto#L286}
  ///
  // clang-format on
  StatusOr<google::cloud::cpp::bigquery::v2::TestIamPermissionsResponse>
  TestIamPermissions(
      std::string const& resource,
      google::cloud::cpp::bigquery::v2::TestIamPermissionsRequest const&
          test_iam_permissions_request_resource,
      Options opts = {});

  // clang-format off
  ///
  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of permissions, not
  /// a `NOT_FOUND` error. Note: This operation is designed to be used for
  /// building permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  /// https://cloud.google.com/bigquery/docs/reference/rest/v2/rowAccessPolicies/testIamPermissions
  ///
  /// @param request Unary RPCs, such as the one wrapped by this
  ///     function, receive a single `request` proto message which includes all
  ///     the inputs for the RPC. In this case, the proto message is a
  ///     [google.cloud.cpp.bigquery.row_access_policies.v2.TestIamPermissionsRequest].
  ///     Proto messages are converted to C++ classes by Protobuf, using the
  ///     [Protobuf mapping rules].
  /// @param opts Optional. Override the class-level options, such as retry and
  ///     backoff policies.
  /// @return the result of the RPC. The response message type
  ///     ([google.cloud.cpp.bigquery.v2.TestIamPermissionsResponse])
  ///     is mapped to a C++ class using the [Protobuf mapping rules].
  ///     If the request fails, the [`StatusOr`] contains the error details.
  ///
  /// [Protobuf mapping rules]: https://protobuf.dev/reference/cpp/cpp-generated/
  /// [input iterator requirements]: https://en.cppreference.com/w/cpp/named_req/InputIterator
  /// [`std::string`]: https://en.cppreference.com/w/cpp/string/basic_string
  /// [`future`]: @ref google::cloud::future
  /// [`StatusOr`]: @ref google::cloud::StatusOr
  /// [`Status`]: @ref google::cloud::Status
  /// [google.cloud.cpp.bigquery.row_access_policies.v2.TestIamPermissionsRequest]: @cloud_cpp_reference_link{google/cloud/bigquery/row_access_policies/v2/row_access_policies.proto#L116}
  /// [google.cloud.cpp.bigquery.v2.TestIamPermissionsResponse]: @cloud_cpp_reference_link{google/cloud/bigquery/v2/internal/common_003.proto#L286}
  ///
  // clang-format on
  StatusOr<google::cloud::cpp::bigquery::v2::TestIamPermissionsResponse>
  TestIamPermissions(google::cloud::cpp::bigquery::row_access_policies::v2::
                         TestIamPermissionsRequest const& request,
                     Options opts = {});

 private:
  std::shared_ptr<RowAccessPoliciesConnection> connection_;
  Options options_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_row_access_policies_v2
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_ROW_ACCESS_POLICIES_V2_ROW_ACCESS_POLICIES_CLIENT_H
