// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/bigquery/projects/v2/projects.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_PROJECTS_V2_INTERNAL_PROJECTS_REST_LOGGING_DECORATOR_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_PROJECTS_V2_INTERNAL_PROJECTS_REST_LOGGING_DECORATOR_H

#include "google/cloud/bigquery/projects/v2/internal/projects_rest_stub.h"
#include "google/cloud/future.h"
#include "google/cloud/internal/rest_context.h"
#include "google/cloud/tracing_options.h"
#include "google/cloud/version.h"
#include <google/cloud/bigquery/projects/v2/projects.pb.h>
#include <memory>
#include <set>
#include <string>

namespace google {
namespace cloud {
namespace bigquery_projects_v2_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class ProjectsRestLogging : public ProjectsRestStub {
 public:
  ~ProjectsRestLogging() override = default;
  ProjectsRestLogging(std::shared_ptr<ProjectsRestStub> child,
                       TracingOptions tracing_options,
                       std::set<std::string> components);

  StatusOr<google::cloud::cpp::bigquery::v2::GetServiceAccountResponse> GetServiceAccount(
      google::cloud::rest_internal::RestContext& rest_context,
      Options const& options, google::cloud::cpp::bigquery::projects::v2::GetServiceAccountRequest const& request) override;

  StatusOr<google::cloud::cpp::bigquery::v2::ProjectList> ListProjects(
      google::cloud::rest_internal::RestContext& rest_context,
      Options const& options, google::cloud::cpp::bigquery::projects::v2::ListProjectsRequest const& request) override;

 private:
  std::shared_ptr<ProjectsRestStub> child_;
  TracingOptions tracing_options_;
  std::set<std::string> components_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_projects_v2_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_PROJECTS_V2_INTERNAL_PROJECTS_REST_LOGGING_DECORATOR_H
