// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/bigquery/projects/v2/projects.proto

#include "google/cloud/bigquery/projects/v2/internal/projects_rest_stub.h"
#include "google/cloud/common_options.h"
#include "google/cloud/internal/absl_str_cat_quiet.h"
#include "google/cloud/internal/rest_stub_helpers.h"
#include "google/cloud/status_or.h"
#include <google/cloud/bigquery/projects/v2/projects.pb.h>
#include <memory>
#include <utility>

namespace google {
namespace cloud {
namespace bigquery_projects_v2_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

DefaultProjectsRestStub::DefaultProjectsRestStub(Options options)
    : service_(rest_internal::MakePooledRestClient(
          options.get<EndpointOption>(), options)),
      options_(std::move(options)) {}

DefaultProjectsRestStub::DefaultProjectsRestStub(
    std::shared_ptr<rest_internal::RestClient> service, Options options)
    : service_(std::move(service)), options_(std::move(options)) {}

StatusOr<google::cloud::cpp::bigquery::v2::GetServiceAccountResponse>
DefaultProjectsRestStub::GetServiceAccount(
    google::cloud::rest_internal::RestContext& rest_context,
    Options const& options,
    google::cloud::cpp::bigquery::projects::v2::GetServiceAccountRequest const&
        request) {
  return rest_internal::Get<
      google::cloud::cpp::bigquery::v2::GetServiceAccountResponse>(
      *service_, rest_context, request, false,
      absl::StrCat("/", "bigquery", "/",
                   rest_internal::DetermineApiVersion("v2", options), "/",
                   "projects", "/", request.project_id(), "/",
                   "serviceAccount"));
}

StatusOr<google::cloud::cpp::bigquery::v2::ProjectList>
DefaultProjectsRestStub::ListProjects(
    google::cloud::rest_internal::RestContext& rest_context,
    Options const& options,
    google::cloud::cpp::bigquery::projects::v2::ListProjectsRequest const&
        request) {
  return rest_internal::Get<google::cloud::cpp::bigquery::v2::ProjectList>(
      *service_, rest_context, request, false,
      absl::StrCat("/bigquery/",
                   rest_internal::DetermineApiVersion("v2", options),
                   "/projects"),
      rest_internal::TrimEmptyQueryParameters(
          {std::make_pair("max_results", std::to_string(request.max_results())),
           std::make_pair("page_token", request.page_token())}));
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_projects_v2_internal
}  // namespace cloud
}  // namespace google
