// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/bigquery/projects/v2/projects.proto

#include "google/cloud/bigquery/projects/v2/internal/projects_tracing_connection.h"
#include "google/cloud/internal/opentelemetry.h"
#include <memory>

namespace google {
namespace cloud {
namespace bigquery_projects_v2_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

#ifdef GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY

ProjectsTracingConnection::ProjectsTracingConnection(
    std::shared_ptr<bigquery_projects_v2::ProjectsConnection> child)
    : child_(std::move(child)) {}

StatusOr<google::cloud::cpp::bigquery::v2::GetServiceAccountResponse>
ProjectsTracingConnection::GetServiceAccount(google::cloud::cpp::bigquery::projects::v2::GetServiceAccountRequest const& request) {
  auto span = internal::MakeSpan("bigquery_projects_v2::ProjectsConnection::GetServiceAccount");
  auto scope = opentelemetry::trace::Scope(span);
  return internal::EndSpan(*span, child_->GetServiceAccount(request));
}

StatusOr<google::cloud::cpp::bigquery::v2::ProjectList>
ProjectsTracingConnection::ListProjects(google::cloud::cpp::bigquery::projects::v2::ListProjectsRequest const& request) {
  auto span = internal::MakeSpan("bigquery_projects_v2::ProjectsConnection::ListProjects");
  auto scope = opentelemetry::trace::Scope(span);
  return internal::EndSpan(*span, child_->ListProjects(request));
}

#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY

std::shared_ptr<bigquery_projects_v2::ProjectsConnection>
MakeProjectsTracingConnection(
    std::shared_ptr<bigquery_projects_v2::ProjectsConnection> conn) {
#ifdef GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY
  if (internal::TracingEnabled(conn->options())) {
    conn = std::make_shared<ProjectsTracingConnection>(std::move(conn));
  }
#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY
  return conn;
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_projects_v2_internal
}  // namespace cloud
}  // namespace google
