// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/bigquery/jobs/v2/jobs.proto

#include "google/cloud/bigquery/jobs/v2/jobs_connection.h"
#include "google/cloud/bigquery/jobs/v2/internal/jobs_option_defaults.h"
#include "google/cloud/bigquery/jobs/v2/internal/jobs_tracing_connection.h"
#include "google/cloud/bigquery/jobs/v2/jobs_options.h"
#include "google/cloud/background_threads.h"
#include "google/cloud/common_options.h"
#include "google/cloud/credentials.h"
#include "google/cloud/grpc_options.h"
#include "google/cloud/internal/unified_grpc_credentials.h"
#include <memory>

namespace google {
namespace cloud {
namespace bigquery_jobs_v2 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

JobsConnection::~JobsConnection() = default;

StatusOr<google::cloud::cpp::bigquery::v2::JobCancelResponse>
JobsConnection::Cancel(
    google::cloud::cpp::bigquery::jobs::v2::CancelRequest const&) {
  return Status(StatusCode::kUnimplemented, "not implemented");
}

Status JobsConnection::DeleteJob(
    google::cloud::cpp::bigquery::jobs::v2::DeleteJobRequest const&) {
  return Status(StatusCode::kUnimplemented, "not implemented");
}

StatusOr<google::cloud::cpp::bigquery::v2::Job> JobsConnection::GetJob(
    google::cloud::cpp::bigquery::jobs::v2::GetJobRequest const&) {
  return Status(StatusCode::kUnimplemented, "not implemented");
}

StatusOr<google::cloud::cpp::bigquery::v2::GetQueryResultsResponse>
JobsConnection::GetQueryResults(
    google::cloud::cpp::bigquery::jobs::v2::GetQueryResultsRequest const&) {
  return Status(StatusCode::kUnimplemented, "not implemented");
}

StatusOr<google::cloud::cpp::bigquery::v2::Job> JobsConnection::InsertJob(
    google::cloud::cpp::bigquery::jobs::v2::InsertJobRequest const&) {
  return Status(StatusCode::kUnimplemented, "not implemented");
}

StatusOr<google::cloud::cpp::bigquery::v2::JobList> JobsConnection::ListJobs(
    google::cloud::cpp::bigquery::jobs::v2::ListJobsRequest const&) {
  return Status(StatusCode::kUnimplemented, "not implemented");
}

StatusOr<google::cloud::cpp::bigquery::v2::QueryResponse> JobsConnection::Query(
    google::cloud::cpp::bigquery::jobs::v2::QueryRequest const&) {
  return Status(StatusCode::kUnimplemented, "not implemented");
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_jobs_v2
}  // namespace cloud
}  // namespace google
