// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/bigquery/models/v2/models.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_MODELS_V2_INTERNAL_MODELS_REST_CONNECTION_IMPL_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_MODELS_V2_INTERNAL_MODELS_REST_CONNECTION_IMPL_H

#include "google/cloud/bigquery/models/v2/internal/models_rest_stub.h"
#include "google/cloud/bigquery/models/v2/internal/models_retry_traits.h"
#include "google/cloud/bigquery/models/v2/models_connection.h"
#include "google/cloud/bigquery/models/v2/models_connection_idempotency_policy.h"
#include "google/cloud/bigquery/models/v2/models_options.h"
#include "google/cloud/background_threads.h"
#include "google/cloud/backoff_policy.h"
#include "google/cloud/options.h"
#include "google/cloud/status_or.h"
#include "google/cloud/version.h"
#include <memory>

namespace google {
namespace cloud {
namespace bigquery_models_v2_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class ModelsRestConnectionImpl : public bigquery_models_v2::ModelsConnection {
 public:
  ~ModelsRestConnectionImpl() override = default;

  ModelsRestConnectionImpl(
      std::unique_ptr<google::cloud::BackgroundThreads> background,
      std::shared_ptr<bigquery_models_v2_internal::ModelsRestStub> stub,
      Options options);

  Options options() override { return options_; }

  Status DeleteModel(
      google::cloud::cpp::bigquery::models::v2::DeleteModelRequest const&
          request) override;

  StatusOr<google::cloud::cpp::bigquery::v2::Model> GetModel(
      google::cloud::cpp::bigquery::models::v2::GetModelRequest const& request)
      override;

  StatusOr<google::cloud::cpp::bigquery::v2::ListModelsResponse> ListModels(
      google::cloud::cpp::bigquery::models::v2::ListModelsRequest const&
          request) override;

  StatusOr<google::cloud::cpp::bigquery::v2::Model> PatchModel(
      google::cloud::cpp::bigquery::models::v2::PatchModelRequest const&
          request) override;

 private:
  static std::unique_ptr<bigquery_models_v2::ModelsRetryPolicy> retry_policy(
      Options const& options) {
    return options.get<bigquery_models_v2::ModelsRetryPolicyOption>()->clone();
  }

  static std::unique_ptr<BackoffPolicy> backoff_policy(Options const& options) {
    return options.get<bigquery_models_v2::ModelsBackoffPolicyOption>()
        ->clone();
  }

  static std::unique_ptr<bigquery_models_v2::ModelsConnectionIdempotencyPolicy>
  idempotency_policy(Options const& options) {
    return options
        .get<bigquery_models_v2::ModelsConnectionIdempotencyPolicyOption>()
        ->clone();
  }

  std::unique_ptr<google::cloud::BackgroundThreads> background_;
  std::shared_ptr<bigquery_models_v2_internal::ModelsRestStub> stub_;
  Options options_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_models_v2_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_MODELS_V2_INTERNAL_MODELS_REST_CONNECTION_IMPL_H
