// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/bigquery/routines/v2/routines.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_ROUTINES_V2_ROUTINES_CONNECTION_IDEMPOTENCY_POLICY_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_ROUTINES_V2_ROUTINES_CONNECTION_IDEMPOTENCY_POLICY_H

#include "google/cloud/idempotency.h"
#include "google/cloud/version.h"
#include <google/cloud/bigquery/routines/v2/routines.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace bigquery_routines_v2 {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class RoutinesConnectionIdempotencyPolicy {
 public:
  virtual ~RoutinesConnectionIdempotencyPolicy();

  /// Create a new copy of this object.
  virtual std::unique_ptr<RoutinesConnectionIdempotencyPolicy> clone() const;

  virtual google::cloud::Idempotency
  DeleteRoutine(google::cloud::cpp::bigquery::routines::v2::DeleteRoutineRequest const& request);

  virtual google::cloud::Idempotency
  GetRoutine(google::cloud::cpp::bigquery::routines::v2::GetRoutineRequest const& request);

  virtual google::cloud::Idempotency
  InsertRoutine(google::cloud::cpp::bigquery::routines::v2::InsertRoutineRequest const& request);

  virtual google::cloud::Idempotency
  ListRoutines(google::cloud::cpp::bigquery::routines::v2::ListRoutinesRequest const& request);

  virtual google::cloud::Idempotency
  UpdateRoutine(google::cloud::cpp::bigquery::routines::v2::UpdateRoutineRequest const& request);
};

std::unique_ptr<RoutinesConnectionIdempotencyPolicy>
    MakeDefaultRoutinesConnectionIdempotencyPolicy();

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_routines_v2
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_ROUTINES_V2_ROUTINES_CONNECTION_IDEMPOTENCY_POLICY_H
