// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/bigquery/tabledata/v2/tabledata.proto

#include "google/cloud/bigquery/tabledata/v2/internal/tabledata_rest_connection_impl.h"
#include "google/cloud/bigquery/tabledata/v2/internal/tabledata_rest_stub_factory.h"
#include "google/cloud/common_options.h"
#include "google/cloud/credentials.h"
#include "google/cloud/internal/rest_retry_loop.h"
#include "google/cloud/rest_options.h"
#include <memory>

namespace google {
namespace cloud {
namespace bigquery_tabledata_v2_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

TabledataRestConnectionImpl::TabledataRestConnectionImpl(
    std::unique_ptr<google::cloud::BackgroundThreads> background,
    std::shared_ptr<bigquery_tabledata_v2_internal::TabledataRestStub> stub,
    Options options)
    : background_(std::move(background)),
      stub_(std::move(stub)),
      options_(internal::MergeOptions(std::move(options),
                                      TabledataConnection::options())) {}

StatusOr<google::cloud::cpp::bigquery::v2::TableDataInsertAllResponse>
TabledataRestConnectionImpl::InsertAll(
    google::cloud::cpp::bigquery::tabledata::v2::InsertAllRequest const&
        request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return google::cloud::rest_internal::RestRetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->InsertAll(request),
      [this](
          rest_internal::RestContext& rest_context, Options const& options,
          google::cloud::cpp::bigquery::tabledata::v2::InsertAllRequest const&
              request) {
        return stub_->InsertAll(rest_context, options, request);
      },
      *current, request, __func__);
}

StatusOr<google::cloud::cpp::bigquery::v2::TableDataList>
TabledataRestConnectionImpl::ListTabledata(
    google::cloud::cpp::bigquery::tabledata::v2::ListTabledataRequest const&
        request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return google::cloud::rest_internal::RestRetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->ListTabledata(request),
      [this](rest_internal::RestContext& rest_context, Options const& options,
             google::cloud::cpp::bigquery::tabledata::v2::
                 ListTabledataRequest const& request) {
        return stub_->ListTabledata(rest_context, options, request);
      },
      *current, request, __func__);
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_tabledata_v2_internal
}  // namespace cloud
}  // namespace google
