// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/bigquery/tabledata/v2/tabledata.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_TABLEDATA_V2_INTERNAL_TABLEDATA_REST_LOGGING_DECORATOR_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_TABLEDATA_V2_INTERNAL_TABLEDATA_REST_LOGGING_DECORATOR_H

#include "google/cloud/bigquery/tabledata/v2/internal/tabledata_rest_stub.h"
#include "google/cloud/future.h"
#include "google/cloud/internal/rest_context.h"
#include "google/cloud/tracing_options.h"
#include "google/cloud/version.h"
#include <google/cloud/bigquery/tabledata/v2/tabledata.pb.h>
#include <memory>
#include <set>
#include <string>

namespace google {
namespace cloud {
namespace bigquery_tabledata_v2_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class TabledataRestLogging : public TabledataRestStub {
 public:
  ~TabledataRestLogging() override = default;
  TabledataRestLogging(std::shared_ptr<TabledataRestStub> child,
                       TracingOptions tracing_options,
                       std::set<std::string> components);

  StatusOr<google::cloud::cpp::bigquery::v2::TableDataInsertAllResponse>
  InsertAll(google::cloud::rest_internal::RestContext& rest_context,
            Options const& options,
            google::cloud::cpp::bigquery::tabledata::v2::InsertAllRequest const&
                request) override;

  StatusOr<google::cloud::cpp::bigquery::v2::TableDataList> ListTabledata(
      google::cloud::rest_internal::RestContext& rest_context,
      Options const& options,
      google::cloud::cpp::bigquery::tabledata::v2::ListTabledataRequest const&
          request) override;

 private:
  std::shared_ptr<TabledataRestStub> child_;
  TracingOptions tracing_options_;
  std::set<std::string> components_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_tabledata_v2_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_BIGQUERY_TABLEDATA_V2_INTERNAL_TABLEDATA_REST_LOGGING_DECORATOR_H
