// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/bigquery/jobs/v2/jobs.proto

#include "google/cloud/bigquery/jobs/v2/internal/jobs_rest_connection_impl.h"
#include "google/cloud/bigquery/jobs/v2/internal/jobs_rest_stub_factory.h"
#include "google/cloud/common_options.h"
#include "google/cloud/credentials.h"
#include "google/cloud/internal/rest_retry_loop.h"
#include "google/cloud/rest_options.h"
#include <memory>

namespace google {
namespace cloud {
namespace bigquery_jobs_v2_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

JobsRestConnectionImpl::JobsRestConnectionImpl(
    std::unique_ptr<google::cloud::BackgroundThreads> background,
    std::shared_ptr<bigquery_jobs_v2_internal::JobsRestStub> stub,
    Options options)
    : background_(std::move(background)),
      stub_(std::move(stub)),
      options_(internal::MergeOptions(std::move(options),
                                      JobsConnection::options())) {}

StatusOr<google::cloud::cpp::bigquery::v2::JobCancelResponse>
JobsRestConnectionImpl::Cancel(
    google::cloud::cpp::bigquery::jobs::v2::CancelRequest const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return google::cloud::rest_internal::RestRetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->Cancel(request),
      [this](rest_internal::RestContext& rest_context, Options const& options,
             google::cloud::cpp::bigquery::jobs::v2::CancelRequest const&
                 request) {
        return stub_->Cancel(rest_context, options, request);
      },
      *current, request, __func__);
}

Status JobsRestConnectionImpl::DeleteJob(
    google::cloud::cpp::bigquery::jobs::v2::DeleteJobRequest const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return google::cloud::rest_internal::RestRetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->DeleteJob(request),
      [this](rest_internal::RestContext& rest_context, Options const& options,
             google::cloud::cpp::bigquery::jobs::v2::DeleteJobRequest const&
                 request) {
        return stub_->DeleteJob(rest_context, options, request);
      },
      *current, request, __func__);
}

StatusOr<google::cloud::cpp::bigquery::v2::Job> JobsRestConnectionImpl::GetJob(
    google::cloud::cpp::bigquery::jobs::v2::GetJobRequest const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return google::cloud::rest_internal::RestRetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->GetJob(request),
      [this](rest_internal::RestContext& rest_context, Options const& options,
             google::cloud::cpp::bigquery::jobs::v2::GetJobRequest const&
                 request) {
        return stub_->GetJob(rest_context, options, request);
      },
      *current, request, __func__);
}

StatusOr<google::cloud::cpp::bigquery::v2::GetQueryResultsResponse>
JobsRestConnectionImpl::GetQueryResults(
    google::cloud::cpp::bigquery::jobs::v2::GetQueryResultsRequest const&
        request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return google::cloud::rest_internal::RestRetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->GetQueryResults(request),
      [this](
          rest_internal::RestContext& rest_context, Options const& options,
          google::cloud::cpp::bigquery::jobs::v2::GetQueryResultsRequest const&
              request) {
        return stub_->GetQueryResults(rest_context, options, request);
      },
      *current, request, __func__);
}

StatusOr<google::cloud::cpp::bigquery::v2::Job>
JobsRestConnectionImpl::InsertJob(
    google::cloud::cpp::bigquery::jobs::v2::InsertJobRequest const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return google::cloud::rest_internal::RestRetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->InsertJob(request),
      [this](rest_internal::RestContext& rest_context, Options const& options,
             google::cloud::cpp::bigquery::jobs::v2::InsertJobRequest const&
                 request) {
        return stub_->InsertJob(rest_context, options, request);
      },
      *current, request, __func__);
}

StatusOr<google::cloud::cpp::bigquery::v2::JobList>
JobsRestConnectionImpl::ListJobs(
    google::cloud::cpp::bigquery::jobs::v2::ListJobsRequest const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return google::cloud::rest_internal::RestRetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->ListJobs(request),
      [this](rest_internal::RestContext& rest_context, Options const& options,
             google::cloud::cpp::bigquery::jobs::v2::ListJobsRequest const&
                 request) {
        return stub_->ListJobs(rest_context, options, request);
      },
      *current, request, __func__);
}

StatusOr<google::cloud::cpp::bigquery::v2::QueryResponse>
JobsRestConnectionImpl::Query(
    google::cloud::cpp::bigquery::jobs::v2::QueryRequest const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return google::cloud::rest_internal::RestRetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->Query(request),
      [this](
          rest_internal::RestContext& rest_context, Options const& options,
          google::cloud::cpp::bigquery::jobs::v2::QueryRequest const& request) {
        return stub_->Query(rest_context, options, request);
      },
      *current, request, __func__);
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace bigquery_jobs_v2_internal
}  // namespace cloud
}  // namespace google
